from __future__ import annotations

from datetime import datetime, timezone
from decimal import Decimal
from typing import Annotated, Literal
from uuid import UUID

from pydantic import (
    AwareDatetime, BaseModel, ConfigDict, Field, TypeAdapter,
    ValidationInfo, field_validator, model_validator,
)


class PlannerModel(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True, str_strip_whitespace=True)


class RequirementFields(PlannerModel):
    categoryId: UUID | None = None
    category: str | None = Field(default=None, min_length=1, max_length=120)
    requiredQuantity: Decimal = Field(gt=0, max_digits=18, decimal_places=3, allow_inf_nan=False)
    unit: str = Field(min_length=1, max_length=32)
    maximumBudget: Decimal = Field(gt=0, max_digits=18, decimal_places=2, allow_inf_nan=False)
    deadline: AwareDatetime
    notes: str = Field(default="", max_length=2000)

    @field_validator("categoryId")
    @classmethod
    def nonempty_category_id(cls, value: UUID | None) -> UUID | None:
        if value is not None and value.int == 0:
            raise ValueError("categoryId must not be empty.")
        return value

    @field_validator("requiredQuantity", "maximumBudget", mode="before")
    @classmethod
    def reject_boolean_numbers(cls, value: object) -> object:
        if isinstance(value, bool):
            raise ValueError("Boolean values are not quantities or budgets.")
        return value

    @field_validator("deadline", mode="before")
    @classmethod
    def reject_numeric_deadline(cls, value: object) -> object:
        if not isinstance(value, (str, datetime)):
            raise ValueError("Use a timezone-aware datetime or ISO timestamp.")
        return value

    @field_validator("deadline")
    @classmethod
    def utc_deadline(cls, value: datetime) -> datetime:
        return value.astimezone(timezone.utc)

    @model_validator(mode="after")
    def category_required(self) -> RequirementFields:
        if self.categoryId is None and self.category is None:
            raise ValueError("Either categoryId or category is required.")
        return self


class StoredBuyerRequest(RequirementFields):
    """Read DTO from the trusted backend, not a new persistence model."""

    id: UUID
    buyerId: UUID
    latitude: Decimal = Field(ge=-90, le=90, max_digits=9, decimal_places=6, allow_inf_nan=False)
    longitude: Decimal = Field(ge=-180, le=180, max_digits=9, decimal_places=6, allow_inf_nan=False)
    status: Literal[
        "DRAFT", "OPEN", "MATCHING", "MATCH_FOUND", "PENDING_APPROVAL",
        "APPROVED", "REJECTED", "COMPLETED", "CANCELLED",
    ] | None = None
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None

    @field_validator("id", "buyerId")
    @classmethod
    def nonempty_id(cls, value: UUID) -> UUID:
        if value.int == 0:
            raise ValueError("Stored IDs must not be empty.")
        return value

    @field_validator("latitude", "longitude", mode="before")
    @classmethod
    def reject_boolean_coordinates(cls, value: object) -> object:
        if isinstance(value, bool):
            raise ValueError("Boolean values are not coordinates.")
        return value

    @field_validator("deadline")
    @classmethod
    def future_deadline(cls, value: datetime, info: ValidationInfo) -> datetime:
        now = (info.context or {}).get("now", datetime.now(timezone.utc))
        if value <= now:
            raise ValueError("deadline must be in the future.")
        return value


class PlannerRequest(PlannerModel):
    buyerRequest: StoredBuyerRequest
    objective: str | None = Field(default=None, max_length=2000)


class NormalizedCriteria(RequirementFields):
    buyerUserId: UUID
    targetLatitude: Decimal = Field(ge=-90, le=90, max_digits=9, decimal_places=6, allow_inf_nan=False)
    targetLongitude: Decimal = Field(ge=-180, le=180, max_digits=9, decimal_places=6, allow_inf_nan=False)


# Literal tuples make the dependency references and their order part of the schema,
# not instructions supplied by a user or generated by a model.
class MatchingPlanStep(PlannerModel):
    stepOrder: Literal[1] = 1
    agent: Literal["MaterialMatchingAgent"] = "MaterialMatchingAgent"
    action: Literal["match_materials"] = "match_materials"
    requiredInputs: tuple[
        Literal["normalizedCriteria.buyerUserId"],
        Literal["normalizedCriteria.categoryId"], Literal["normalizedCriteria.category"],
        Literal["normalizedCriteria.requiredQuantity"], Literal["normalizedCriteria.unit"],
        Literal["normalizedCriteria.maximumBudget"], Literal["normalizedCriteria.deadline"],
    ] = (
        "normalizedCriteria.buyerUserId",
        "normalizedCriteria.categoryId", "normalizedCriteria.category",
        "normalizedCriteria.requiredQuantity", "normalizedCriteria.unit",
        "normalizedCriteria.maximumBudget", "normalizedCriteria.deadline",
    )


class LogisticsPlanStep(PlannerModel):
    stepOrder: Literal[2] = 2
    agent: Literal["LogisticsAgent"] = "LogisticsAgent"
    action: Literal["estimate_logistics"] = "estimate_logistics"
    requiredInputs: tuple[
        Literal["step1.candidates"], Literal["normalizedCriteria.requiredQuantity"],
        Literal["normalizedCriteria.unit"], Literal["normalizedCriteria.targetLatitude"],
        Literal["normalizedCriteria.targetLongitude"], Literal["normalizedCriteria.deadline"],
    ] = (
        "step1.candidates", "normalizedCriteria.requiredQuantity", "normalizedCriteria.unit",
        "normalizedCriteria.targetLatitude", "normalizedCriteria.targetLongitude",
        "normalizedCriteria.deadline",
    )


class ValidationPlanStep(PlannerModel):
    stepOrder: Literal[3] = 3
    agent: Literal["ValidationAgent"] = "ValidationAgent"
    action: Literal["validate_recommendation"] = "validate_recommendation"
    requiredInputs: tuple[
        Literal["normalizedCriteria"], Literal["step1.candidates"], Literal["step2.logistics"],
    ] = ("normalizedCriteria", "step1.candidates", "step2.logistics")


class ApprovalPlanStep(PlannerModel):
    stepOrder: Literal[4] = 4
    agent: Literal["ManagerApproval"] = "ManagerApproval"
    action: Literal["request_manager_approval"] = "request_manager_approval"
    requiredInputs: tuple[
        Literal["buyerRequestId"], Literal["step3.validationResult"],
    ] = ("buyerRequestId", "step3.validationResult")


class PlannerIssue(PlannerModel):
    field: str
    code: str
    message: str


class PlannerSuccess(PlannerModel):
    status: Literal["ok"] = "ok"
    buyerRequestId: UUID
    normalizedCriteria: NormalizedCriteria
    planSteps: tuple[MatchingPlanStep, LogisticsPlanStep, ValidationPlanStep, ApprovalPlanStep]
    warnings: tuple[Literal["OBJECTIVE_NOT_APPLIED", "NOTES_ARE_UNTRUSTED_DATA"], ...] = ()


class PlannerFailure(PlannerModel):
    status: Literal["invalid_input"] = "invalid_input"
    normalizedCriteria: None = None
    planSteps: tuple[()] = ()
    issues: tuple[PlannerIssue, ...] = Field(min_length=1)


PlannerResponse = Annotated[PlannerSuccess | PlannerFailure, Field(discriminator="status")]
planner_response_adapter = TypeAdapter(PlannerResponse)


def canonical_plan() -> tuple[MatchingPlanStep, LogisticsPlanStep, ValidationPlanStep, ApprovalPlanStep]:
    return MatchingPlanStep(), LogisticsPlanStep(), ValidationPlanStep(), ApprovalPlanStep()
