// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SurplusLink.Api.Data;

#nullable disable

namespace SurplusLink.Api.Data.Migrations
{
    [DbContext(typeof(SurplusLinkDbContext))]
    [Migration("20260924053840_AddCategoryAllowedUnits")]
    partial class AddCategoryAllowedUnits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SurplusLink.Api.Models.AgentStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentWorkflowId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("DurationMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("OutputJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ValidationJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("AgentWorkflowId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("UX_AgentSteps_Workflow_Sequence");

                    b.ToTable("AgentSteps", null, t =>
                        {
                            t.HasCheckConstraint("CK_AgentSteps_RetryCount_NonNegative", "\"RetryCount\" >= 0");
                        });
                });

            modelBuilder.Entity("SurplusLink.Api.Models.AgentToolCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentStepId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("DurationMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("OutputJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("AgentStepId")
                        .HasDatabaseName("IX_AgentToolCalls_AgentStepId");

                    b.ToTable("AgentToolCalls", null, t =>
                        {
                            t.HasCheckConstraint("CK_AgentToolCalls_RetryCount_NonNegative", "\"RetryCount\" >= 0");
                        });
                });

            modelBuilder.Entity("SurplusLink.Api.Models.AgentWorkflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Decision")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ErrorJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("MaterialMatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MaterialRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("OutputJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ValidationJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("MaterialMatchId")
                        .HasDatabaseName("IX_AgentWorkflows_MaterialMatchId");

                    b.HasIndex("MaterialRequestId")
                        .HasDatabaseName("IX_AgentWorkflows_MaterialRequestId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_AgentWorkflows_Status");

                    b.ToTable("AgentWorkflows", null, t =>
                        {
                            t.HasCheckConstraint("CK_AgentWorkflows_RetryCount_NonNegative", "\"RetryCount\" >= 0");
                        });
                });

            modelBuilder.Entity("SurplusLink.Api.Models.Approval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentWorkflowId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DecidedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("DecidedByUserId");

                    b.HasIndex("AgentWorkflowId", "DecidedAtUtc")
                        .HasDatabaseName("IX_Approvals_Workflow_DecidedAtUtc");

                    b.ToTable("Approvals", (string)null);
                });

            modelBuilder.Entity("SurplusLink.Api.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_AuditLogs");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("EntityType", "EntityId", "CreatedAtUtc")
                        .HasDatabaseName("IX_AuditLogs_EntityType_EntityId_CreatedAtUtc");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("SurplusLink.Api.Models.BuyerRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeadlineUtc");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("MaximumBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Budget");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("RequiredQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("Quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("PK_MaterialRequests");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_MaterialRequests_CategoryId");

                    b.HasIndex("Deadline")
                        .HasDatabaseName("IX_MaterialRequests_DeadlineUtc");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_MaterialRequests_Status");

                    b.HasIndex("BuyerId", "CreatedAtUtc")
                        .HasDatabaseName("IX_MaterialRequests_BuyerId_CreatedAtUtc");

                    b.HasIndex("Status", "Deadline")
                        .HasDatabaseName("IX_MaterialRequests_Status_DeadlineUtc");

                    b.ToTable("MaterialRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_MaterialRequests_Budget_Positive", "\"Budget\" > 0");

                            t.HasCheckConstraint("CK_MaterialRequests_Coordinates_Valid", "(\"Latitude\" IS NULL AND \"Longitude\" IS NULL) OR (\"Latitude\" IS NOT NULL AND \"Longitude\" IS NOT NULL AND \"Latitude\" BETWEEN -90 AND 90 AND \"Longitude\" BETWEEN -180 AND 180)");

                            t.HasCheckConstraint("CK_MaterialRequests_Quantity_Positive", "\"Quantity\" > 0");

                            t.HasCheckConstraint("CK_MaterialRequests_Status_Valid", "\"Status\" IN ('DRAFT', 'OPEN', 'MATCHING', 'MATCH_FOUND', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'COMPLETED', 'CANCELLED')");

                            t.HasCheckConstraint("CK_MaterialRequests_Unit_NotBlank", "length(btrim(\"Unit\")) > 0");
                        });
                });

            modelBuilder.Entity("SurplusLink.Api.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string[]>("AllowedUnits")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("citext");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_Categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Categories_Name");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000101"),
                            AllowedUnits = new[] { "pcs", "m", "m2", "m3", "kg", "g", "l", "bag", "box", "set", "roll", "sheet", "tonne", "pair" },
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cement",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000102"),
                            AllowedUnits = new[] { "pcs", "m", "m2", "m3", "kg", "g", "l", "bag", "box", "set", "roll", "sheet", "tonne", "pair" },
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Steel",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000103"),
                            AllowedUnits = new[] { "pcs", "m", "m2", "m3", "kg", "g", "l", "bag", "box", "set", "roll", "sheet", "tonne", "pair" },
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Timber",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000104"),
                            AllowedUnits = new[] { "pcs", "m", "m2", "m3", "kg", "g", "l", "bag", "box", "set", "roll", "sheet", "tonne", "pair" },
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Bricks",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000105"),
                            AllowedUnits = new[] { "pcs", "m", "m2", "m3", "kg", "g", "l", "bag", "box", "set", "roll", "sheet", "tonne", "pair" },
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Aggregates",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000106"),
                            AllowedUnits = new[] { "pcs", "m", "m2", "m3", "kg", "g", "l", "bag", "box", "set", "roll", "sheet", "tonne", "pair" },
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tiles",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SurplusLink.Api.Models.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AvailableUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("ReservedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("PK_Listings");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Listings_CategoryId");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("IX_Listings_SellerId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Listings_Status");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("IX_Listings_Latitude_Longitude");

                    b.HasIndex("Status", "AvailableUntil")
                        .HasDatabaseName("IX_Listings_Status_AvailableUntil");

                    b.ToTable("Listings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Listings_Coordinates_Valid", "(\"Latitude\" IS NULL AND \"Longitude\" IS NULL) OR (\"Latitude\" BETWEEN -90 AND 90 AND \"Longitude\" BETWEEN -180 AND 180)");

                            t.HasCheckConstraint("CK_Listings_Price_Positive", "\"UnitPrice\" > 0");

                            t.HasCheckConstraint("CK_Listings_Quantity_Positive", "\"Quantity\" > 0");

                            t.HasCheckConstraint("CK_Listings_ReservedQuantity_Range", "\"ReservedQuantity\" >= 0 AND \"ReservedQuantity\" <= \"Quantity\"");
                        });
                });

            modelBuilder.Entity("SurplusLink.Api.Models.ListingPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_ListingPhotos");

                    b.HasIndex("ListingId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_ListingPhotos_ListingId_SortOrder");

                    b.ToTable("ListingPhotos", null, t =>
                        {
                            t.HasCheckConstraint("CK_ListingPhotos_SortOrder_NonNegative", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("SurplusLink.Api.Models.MaterialMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("Distance")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal?>("DurationMinutes")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("EstimatedTransportCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaterialRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasDefaultValue("GENERATED");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("PK_Matches");

                    b.HasIndex("ListingId");

                    b.HasIndex("MaterialRequestId", "ListingId")
                        .IsUnique()
                        .HasDatabaseName("UX_Matches_MaterialRequestId_ListingId");

                    b.HasIndex("MaterialRequestId", "Score")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Matches_MaterialRequestId_Score");

                    b.ToTable("Matches", null, t =>
                        {
                            t.HasCheckConstraint("CK_Matches_Distance", "\"Distance\" IS NULL OR \"Distance\" >= 0");

                            t.HasCheckConstraint("CK_Matches_RejectionReason", "(\"Status\" = 'REJECTED' AND length(btrim(\"RejectionReason\")) > 0 AND \"RejectionReason\" IS NOT NULL) OR (\"Status\" <> 'REJECTED' AND \"RejectionReason\" IS NULL)");

                            t.HasCheckConstraint("CK_Matches_Score_Range", "\"Score\" >= 0 AND \"Score\" <= 1");

                            t.HasCheckConstraint("CK_Matches_Status", "\"Status\" IN ('GENERATED', 'RANKED', 'ROUTED', 'ROUTE_FAILED', 'REJECTED')");

                            t.HasCheckConstraint("CK_Matches_TransportCost", "\"EstimatedTransportCost\" IS NULL OR \"EstimatedTransportCost\" >= 0");
                        });
                });

            modelBuilder.Entity("SurplusLink.Api.Models.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("MaterialMatchId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("TotalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("UnitValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId")
                        .HasDatabaseName("IX_Offers_BuyerId");

                    b.HasIndex("MaterialMatchId");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("IX_Offers_SellerId");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("IX_Offers_Status_CreatedAtUtc");

                    b.ToTable("Offers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Offers_BuyerSeller_Different", "\"BuyerId\" <> \"SellerId\"");

                            t.HasCheckConstraint("CK_Offers_Quantity_Positive", "\"Quantity\" > 0");

                            t.HasCheckConstraint("CK_Offers_TotalValue_Positive", "\"TotalValue\" > 0");

                            t.HasCheckConstraint("CK_Offers_UnitValue_Positive", "\"UnitValue\" > 0");
                        });
                });

            modelBuilder.Entity("SurplusLink.Api.Models.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaterialRequestId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_Reservations");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("IX_Reservations_ListingId");

                    b.HasIndex("MaterialRequestId")
                        .HasDatabaseName("IX_Reservations_MaterialRequestId");

                    b.ToTable("Reservations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Reservations_Quantity_Positive", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("SurplusLink.Api.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("ReservedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("TotalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId")
                        .HasDatabaseName("IX_Transactions_BuyerId");

                    b.HasIndex("OfferId");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("IX_Transactions_SellerId");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("IX_Transactions_Status_CreatedAtUtc");

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transactions_BuyerSeller_Different", "\"BuyerId\" <> \"SellerId\"");

                            t.HasCheckConstraint("CK_Transactions_Quantity_Positive", "\"Quantity\" > 0");

                            t.HasCheckConstraint("CK_Transactions_ReservedQuantity_Range", "\"ReservedQuantity\" >= 0 AND \"ReservedQuantity\" <= \"Quantity\"");

                            t.HasCheckConstraint("CK_Transactions_TotalValue_Positive", "\"TotalValue\" > 0");
                        });
                });

            modelBuilder.Entity("SurplusLink.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("BusinessName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("citext");

                    b.Property<string>("FullName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_Users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Email");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SurplusLink.Api.Models.UserRoleAssignment", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("UserId", "Role");

                    b.ToTable("UserRoleAssignments", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserRoleAssignments_Role", "\"Role\" IN ('SELLER', 'BUYER', 'MANAGER')");
                        });
                });

            modelBuilder.Entity("SurplusLink.Api.Models.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("MaterialMatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK_Workflows");

                    b.HasIndex("MaterialMatchId")
                        .IsUnique()
                        .HasDatabaseName("UX_Workflows_MaterialMatchId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Workflows_Status");

                    b.ToTable("Workflows", (string)null);
                });

            modelBuilder.Entity("SurplusLink.Api.Models.AgentStep", b =>
                {
                    b.HasOne("SurplusLink.Api.Models.AgentWorkflow", "AgentWorkflow")
                        .WithMany("Steps")
                        .HasForeignKey("AgentWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentWorkflow");
                });

            modelBuilder.Entity("SurplusLink.Api.Models.AgentToolCall", b =>
                {
                    b.HasOne("SurplusLink.Api.Models.AgentStep", "AgentStep")
                        .WithMany("ToolCalls")
                        .HasForeignKey("AgentStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentStep");
                });

            modelBuilder.Entity("SurplusLink.Api.Models.AgentWorkflow", b =>
                {
                    b.HasOne("SurplusLink.Api.Models.MaterialMatch", "MaterialMatch")
                        .WithMany()
                        .HasForeignKey("MaterialMatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SurplusLink.Api.Models.BuyerRequest", "MaterialRequest")
                        .WithMany()
                        .HasForeignKey("MaterialRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MaterialMatch");

                    b.Navigation("MaterialRequest");
                });

            modelBuilder.Entity("SurplusLink.Api.Models.Approval", b =>
                {
                    b.HasOne("SurplusLink.Api.Models.AgentWorkflow", "AgentWorkflow")
                        .WithMany("Approvals")
                        .HasForeignKey("AgentWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SurplusLink.Api.Models.User", "DecidedByUser")
                        .WithMany()
                        .HasForeignKey("DecidedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgentWorkflow");

                    b.Navigation("DecidedByUser");
                });

            modelBuilder.Entity("SurplusLink.Api.Models.AuditLog", b =>
                {
                    b.HasOne("SurplusLink.Api.Models.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_AuditLogs_Users_ActorUserId");

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("SurplusLink.Api.Models.BuyerRequest", b =>
                {
                    b.HasOne("SurplusLink.Api.Models.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_MaterialRequests_Users_BuyerId");

                    b.HasOne("SurplusLink.Api.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_MaterialRequests_Categories_CategoryId");

                    b.Navigation("Buyer");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SurplusLink.Api.Models.Listing", b =>
                {
                    b.HasOne("SurplusLink.Api.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Listings_Categories_CategoryId");

                    b.HasOne("SurplusLink.Api.Models.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Listings_Users_SellerId");

                    b.Navigation("Category");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("SurplusLink.Api.Models.ListingPhoto", b =>
                {
                    b.HasOne("SurplusLink.Api.Models.Listing", "Listing")
                        .WithMany("Photos")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ListingPhotos_Listings_ListingId");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("SurplusLink.Api.Models.MaterialMatch", b =>
                {
                    b.HasOne("SurplusLink.Api.Models.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Matches_Listings_ListingId");

                    b.HasOne("SurplusLink.Api.Models.BuyerRequest", "MaterialRequest")
                        .WithMany()
                        .HasForeignKey("MaterialRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Matches_MaterialRequests_MaterialRequestId");

                    b.Navigation("Listing");

                    b.Navigation("MaterialRequest");
                });

            modelBuilder.Entity("SurplusLink.Api.Models.Offer", b =>
                {
                    b.HasOne("SurplusLink.Api.Models.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SurplusLink.Api.Models.MaterialMatch", "MaterialMatch")
                        .WithMany()
                        .HasForeignKey("MaterialMatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SurplusLink.Api.Models.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("MaterialMatch");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("SurplusLink.Api.Models.Reservation", b =>
                {
                    b.HasOne("SurplusLink.Api.Models.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Reservations_Listings_ListingId");

                    b.HasOne("SurplusLink.Api.Models.BuyerRequest", "MaterialRequest")
                        .WithMany()
                        .HasForeignKey("MaterialRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Reservations_MaterialRequests_MaterialRequestId");

                    b.Navigation("Listing");

                    b.Navigation("MaterialRequest");
                });

            modelBuilder.Entity("SurplusLink.Api.Models.Transaction", b =>
                {
                    b.HasOne("SurplusLink.Api.Models.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SurplusLink.Api.Models.Offer", "Offer")
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SurplusLink.Api.Models.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Offer");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("SurplusLink.Api.Models.UserRoleAssignment", b =>
                {
                    b.HasOne("SurplusLink.Api.Models.User", "User")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SurplusLink.Api.Models.Workflow", b =>
                {
                    b.HasOne("SurplusLink.Api.Models.MaterialMatch", "MaterialMatch")
                        .WithMany()
                        .HasForeignKey("MaterialMatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Workflows_Matches_MaterialMatchId");

                    b.Navigation("MaterialMatch");
                });

            modelBuilder.Entity("SurplusLink.Api.Models.AgentStep", b =>
                {
                    b.Navigation("ToolCalls");
                });

            modelBuilder.Entity("SurplusLink.Api.Models.AgentWorkflow", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("SurplusLink.Api.Models.Listing", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("SurplusLink.Api.Models.User", b =>
                {
                    b.Navigation("RoleAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
