import { useCallback, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { RequirementBadge, RequirementError, requirementDate, requirementNumber, useRequirementResource } from '../../features/requirements/requirementUi';
import { managerWorkflowsApi, type ManagerWorkflowsApi, type Workflow } from '../../features/workflows/managerWorkflowsApi';

export function ManagerWorkflowDetailsPage({ api = managerWorkflowsApi }: { api?: ManagerWorkflowsApi }) {
  const { workflowId = '' } = useParams(); const load = useCallback(() => api.get(workflowId), [api, workflowId]);
  const resource = useRequirementResource(load); const analytics = useRequirementResource(useCallback(() => api.transactionAnalytics(), [api]));
  const [note, setNote] = useState(''); const [busy, setBusy] = useState(false); const [decisionError, setDecisionError] = useState(''); const [notice, setNotice] = useState('');
  const workflow = resource.data;
  async function decide(action: 'approve' | 'reject' | 'revise') {
    if ((action === 'reject' || action === 'revise') && !note.trim()) { setDecisionError('A note is required for rejection or a revision request.'); return; }
    setBusy(true); setDecisionError(''); setNotice('');
    try { const result = await api[action](workflowId, note); setNote(''); setNotice(action === 'approve' ? 'Approved. A reservation outcome is shown below.' : action === 'reject' ? 'Rejected. No reservation was created.' : 'Revision requested. The workflow has returned to the agent queue.'); await resource.reload(); if (result.status === 'APPROVED') setNotice('Approved. Reservation created for the matched inventory.'); }
    catch (error) { setDecisionError(error instanceof Error ? error.message : 'Unable to save this decision.'); }
    finally { setBusy(false); }
  }
  return <div className="manager-page workflow-page"><Link className="back-link" to="/app/manager/approvals">Back to Pending Approvals</Link><header className="page-heading"><div><p className="eyebrow">Manager review</p><h1>Workflow & recommendation details</h1></div><button className="button button-secondary" type="button" onClick={resource.reload} disabled={resource.loading || busy}>Refresh</button></header>
    {resource.loading && <p role="status">Loading workflow?</p>}{resource.error && <RequirementError message={resource.error} retry={resource.reload} />}
    {workflow && <><section className="manager-panel"><div className="section-heading"><div><h2>Recommendation</h2><p className="muted">Workflow {workflow.id}</p></div><RequirementBadge status={workflow.status} /></div><dl className="detail-grid"><div><dt>Current stage</dt><dd>{workflow.currentStage}</dd></div><div><dt>Started</dt><dd>{requirementDate(workflow.startedAtUtc)}</dd></div><div><dt>Completed</dt><dd>{workflow.completedAtUtc ? requirementDate(workflow.completedAtUtc) : 'In progress'}</dd></div><div><dt>Workflow retries</dt><dd>{workflow.retryCount}</dd></div><div><dt>Match</dt><dd>{workflow.materialMatchId ?? 'Not linked'}</dd></div><div><dt>Request</dt><dd>{workflow.materialRequestId ?? 'Not linked'}</dd></div></dl><h3>Recommendation result</h3><pre className="structured-result">{shortJson(workflow.outputJson)}</pre>{workflow.errorJson && <p className="error-message"><strong>Workflow error:</strong> {shortJson(workflow.errorJson)}</p>}</section>
      <TransactionAnalyticsWidget resource={analytics} />
      <section className="manager-panel"><h2>Agent execution</h2>{workflow.steps.length === 0 ? <p className="empty-state">No agent steps have been recorded.</p> : <ol className="workflow-steps">{workflow.steps.map((step) => <li key={step.id}><div className="section-heading"><strong>{step.sequence}. {step.stage}</strong><RequirementBadge status={step.status} /></div><p className="muted">{duration(step.durationMilliseconds)} ? {step.retryCount} retr{step.retryCount === 1 ? 'y' : 'ies'}</p><p><strong>Result:</strong> {shortJson(step.outputJson)}</p>{step.errorJson && <p className="error-message">{shortJson(step.errorJson)}</p>}<details><summary>Tool calls ({step.toolCalls.length})</summary>{step.toolCalls.length === 0 ? <p className="empty-state">No tool calls recorded.</p> : <ul className="tool-call-list">{step.toolCalls.map((call) => <li key={call.id}><strong>{call.toolName}</strong><RequirementBadge status={call.errorJson ? 'ERROR' : call.completedAtUtc ? 'COMPLETED' : 'RUNNING'} /><span>{duration(call.durationMilliseconds)} ? {call.retryCount} retr{call.retryCount === 1 ? 'y' : 'ies'}</span><p>{shortJson(call.outputJson)}</p>{call.errorJson && <p className="error-message">{shortJson(call.errorJson)}</p>}</li>)}</ul>}</details></li>)}</ol>}</section>
      <section className="manager-panel" aria-labelledby="decision-heading"><h2 id="decision-heading">Manager decision</h2>{canDecide(workflow) ? <><label className="decision-note">Decision note<textarea value={note} maxLength={2000} onChange={(event) => setNote(event.target.value)} placeholder="Required for reject or revision request" /></label>{decisionError && <p className="field-error" role="alert">{decisionError}</p>}{notice && <p className="decision-notice" role="status">{notice}</p>}<div className="action-row"><button type="button" className="button button-primary" disabled={busy} onClick={() => void decide('approve')}>Approve</button><button type="button" className="button button-danger" disabled={busy} onClick={() => void decide('reject')}>Reject</button><button type="button" className="button button-secondary" disabled={busy} onClick={() => void decide('revise')}>Request revision</button></div></> : <Outcome workflow={workflow} />}</section>
      <section className="manager-panel"><h2>Decision audit & history</h2>{workflow.approvals.length === 0 ? <p className="empty-state">No manager decisions have been recorded.</p> : <ol className="history-list">{workflow.approvals.map((approval) => <li key={approval.id}><strong>{approval.decision.replaceAll('_', ' ')}</strong><span>{requirementDate(approval.decidedAtUtc)} ? Manager {approval.decidedByUserId}</span>{approval.note && <span>?{approval.note}?</span>}</li>)}</ol>}</section>
    </>}</div>;
}
function TransactionAnalyticsWidget({ resource }: { resource: { data: import('../../features/workflows/managerWorkflowsApi').TransactionAnalytics | null; error: string | null; loading: boolean; reload: () => void } }) { const data = resource.data; return <section className="manager-panel" aria-labelledby="transaction-analytics"><div className="section-heading"><div><p className="eyebrow">Portfolio context</p><h2 id="transaction-analytics">Transaction analytics</h2></div></div>{resource.loading && <p role="status">Loading transaction analytics?</p>}{resource.error && <RequirementError message={resource.error} retry={resource.reload} label="Retry analytics" />}{data && <div className="analytics-metrics"><div className="analytics-metric"><span>Pending approval</span><strong>{requirementNumber(data.pendingApprovalCount)}</strong></div><div className="analytics-metric"><span>Approved</span><strong>{requirementNumber(data.approvedCount)}</strong></div><div className="analytics-metric"><span>Reserved quantity</span><strong>{requirementNumber(data.reservedQuantity)}</strong></div><div className="analytics-metric"><span>Completed value</span><strong>{requirementNumber(data.completedValue, 2)}</strong><small>{data.completionRate === null ? 'No completion rate yet' : Math.round(data.completionRate * 100) + '% complete'}</small></div></div>}</section>; }
function Outcome({ workflow }: { workflow: Workflow }) { const text = workflow.status === 'APPROVED' ? 'Approved ? reservation created for the matched inventory.' : workflow.status === 'REJECTED' ? 'Rejected ? no reservation was created.' : workflow.status === 'REVISION_REQUESTED' ? 'Revision requested ? awaiting updated agent recommendation.' : 'This workflow is no longer awaiting a decision.'; return <p className="decision-notice">{text}{workflow.decision ? ' Note: ' + workflow.decision : ''}</p>; }
function canDecide(workflow: Workflow) { return workflow.status === 'PENDING_APPROVAL' || workflow.status === 'REVISION_REQUESTED'; }
function duration(value: number | null) { return value === null ? 'Duration unavailable' : value < 1000 ? value + ' ms' : (value / 1000).toFixed(1) + ' s'; }
function shortJson(value: string) { try { const parsed: unknown = JSON.parse(value); const text = JSON.stringify(parsed); return text.length > 260 ? text.slice(0, 257) + '?' : text; } catch { return value.length > 260 ? value.slice(0, 257) + '?' : value || 'No result recorded'; } }
