import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../auth/AuthContext';
import { roleHomePath } from '../routing/roleRoutes';

const heroImages = ['/images/hero/warehouse-timber.png', '/images/hero/reclamation-yard.png', '/images/hero/tiles-and-timber.png', '/images/hero/steel-loading-bay.png'];

export function LandingPage() {
  const { status, user } = useAuth();
  const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false); const [activeSlide, setActiveSlide] = useState(0);
  const authenticated = status === 'authenticated' && user; const accountPath = user ? roleHomePath(user.roles) : '/login';
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 12); window.addEventListener('scroll', onScroll, { passive: true }); return () => window.removeEventListener('scroll', onScroll); }, []);
  useEffect(() => { if (window.matchMedia?.('(prefers-reduced-motion: reduce)').matches) return; const timer = window.setInterval(() => setActiveSlide(current => (current + 1) % heroImages.length), 6000); return () => window.clearInterval(timer); }, []);
  return <main className="landing-page premium-landing">
    <header className={`public-nav ${scrolled ? 'public-nav-scrolled' : ''}`}><a className="public-brand" href="#top" onClick={() => setOpen(false)}><span className="brand-symbol" aria-hidden="true">+</span>SurplusLink</a><button className="menu-toggle" type="button" aria-label="Toggle navigation menu" aria-expanded={open} onClick={() => setOpen(value => !value)}><i /><i /><i /></button><nav className={open ? 'open' : ''} aria-label="Public navigation">{['Home', 'Features', 'How it works', 'Sustainability'].map(label => <a key={label} href={`#${label.toLowerCase().replaceAll(' ', '-')}`} onClick={() => setOpen(false)}>{label}</a>)}<Link className="nav-login" to={accountPath} onClick={() => setOpen(false)}>{authenticated ? 'Open Dashboard' : 'Login'}</Link></nav></header>
    <section id="top" className="hero hero-slideshow"><div className="hero-slides" aria-hidden="true">{heroImages.map((image, index) => <img key={image} src={image} className={index === activeSlide ? 'active' : ''} alt="" />)}</div><div className="hero-overlay" /><div className="hero-copy section-shell"><p className="pill">Construction materials, put back to work</p><h1>Turn Surplus Into <em>Opportunity</em></h1><p className="hero-intro">Connect buyers and sellers of reusable construction materials.</p><div className="hero-actions"><Link className="cta primary" to={accountPath}>{authenticated ? 'Open Dashboard' : 'Login'} <b>-&gt;</b></Link><a className="cta secondary" href="#how-it-works">See how it works</a></div><div className="hero-proof"><span>List surplus materials</span><span>Find project needs</span><span>Compare practical matches</span></div><div className="hero-dots" role="tablist" aria-label="Hero images">{heroImages.map((_, index) => <button key={index} type="button" role="tab" aria-label={`Show hero image ${index + 1}`} aria-selected={index === activeSlide} onClick={() => setActiveSlide(index)} />)}</div></div></section>
    <section id="features" className="section-shell section landing-section"><p className="section-kicker">A clearer material exchange</p><h2>Make reuse easier to <em>act on.</em></h2><p className="section-lead">One controlled workspace for reusable inventory, buyer needs, matching context and accountable review.</p><div className="landing-feature-grid">{[['01', 'List useful surplus', 'Keep quantities, condition, pricing and availability visible.'], ['02', 'Source with context', 'Compare practical material options for a project requirement.'], ['03', 'Review with confidence', 'See logistics and recommendation evidence before decisions.'], ['04', 'Keep value moving', 'Help usable construction materials find another purpose.']].map(([number, title, copy]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section id="how-it-works" className="section-shell section landing-flow"><p className="section-kicker">Simple from the start</p><h2>From listing to <em>reuse.</em></h2><div>{['Share what is available or needed.', 'Review compatible options and logistics.', 'Complete authorised workflow decisions.'].map((copy, index) => <article key={copy}><b>0{index + 1}</b><p>{copy}</p></article>)}</div></section>
    <section id="sustainability" className="landing-impact"><div className="section-shell"><p className="section-kicker">Keep value in circulation</p><h2>Use what already <em>exists.</em></h2><p className="section-lead">SurplusLink makes usable material more visible, supporting more deliberate sourcing and less unnecessary disposal.</p><Link className="cta primary" to={accountPath}>{authenticated ? 'Open Dashboard' : 'Login'} <b>-&gt;</b></Link></div></section>
    <footer className="public-footer"><div className="section-shell"><div><a className="public-brand" href="#top"><span className="brand-symbol" aria-hidden="true">+</span>SurplusLink</a><p>Construction material reuse, made easier.</p></div><div><b>Explore</b><a href="#how-it-works">How it works</a><a href="#features">Features</a><a href="#sustainability">Sustainability</a></div><div><b>Account</b><Link to={accountPath}>{authenticated ? 'Open dashboard' : 'Login'}</Link></div></div></footer>
  </main>;
}
