import { useEffect, useState, type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../auth/AuthContext';
import { roleHomePath } from '../routing/roleRoutes';

type IconName = 'layers' | 'clipboard' | 'compare' | 'route' | 'recycle' | 'pin' | 'check' | 'package' | 'search' | 'history';
const features: Array<[IconName, string, string, string]> = [
  ['layers', 'List what you have', 'Add surplus materials with quantity, condition, pricing, photos and location so they are easier to discover and reuse.', 'Create clear listings'],
  ['clipboard', 'Post what you need', 'Describe the material, quantity, budget, deadline and location your project is looking for.', 'Keep project needs organised'],
  ['compare', 'Find better matches', 'SurplusLink compares compatible listings and requirements to surface practical options worth reviewing.', 'Compare suitable options'],
  ['route', 'Plan the journey', 'See distance, estimated travel time and transport cost alongside each match before moving forward.', 'Understand logistics early'],
];
function Icon({ name, size = 24 }: { name: IconName; size?: number }) {
  const paths: Record<IconName, ReactNode> = {
    layers: <><path d="m12 3 8 4.5-8 4.5-8-4.5L12 3Z" /><path d="m4 12 8 4.5 8-4.5M4 16.5 12 21l8-4.5" /></>, clipboard: <><path d="M9 5h6M9 3h6a2 2 0 0 1 2 2v16H7V5a2 2 0 0 1 2-2Z" /><path d="M10 11h4M10 15h4" /></>, compare: <><path d="M7 3v14M4 6l3-3 3 3M17 21V7m-3 11 3 3 3-3" /><path d="M5 21h14" /></>, route: <><circle cx="6" cy="18" r="2" /><circle cx="18" cy="6" r="2" /><path d="M8 18c7 0 1-8 8-10" /></>, recycle: <><path d="m7 7 2-3 2 3M9 4v7m6 6-2 3-2-3m2 3v-7M5 14l-2-3 3-2m-3 2h7m9 1 2 3-3 2m3-2h-7" /></>, pin: <><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z" /><circle cx="12" cy="10" r="2.5" /></>, check: <><circle cx="12" cy="12" r="9" /><path d="m8 12 2.5 2.5L16 9" /></>, package: <><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9L12 3Z" /><path d="m4 7.5 8 4.5 8-4.5M12 12v9" /></>, search: <><circle cx="10.5" cy="10.5" r="6.5" /><path d="m16 16 4 4" /></>, history: <><path d="M3 12a9 9 0 1 0 3-6.7" /><path d="M3 4v5h5M12 7v5l3 2" /></>,
  };
  return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>;
}
function Reveal({ children, className = '' }: { children: ReactNode; className?: string }) { return <div className={`reveal ${className}`}>{children}</div>; }

export function LandingPage() {
  const { status, user } = useAuth(); const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false);
  const authenticated = status === 'authenticated' && user; const accountPath = user ? roleHomePath(user.roles) : '/login';
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 12); const observer = new IntersectionObserver(entries => entries.forEach(entry => entry.isIntersecting && entry.target.classList.add('is-visible')), { threshold: .12 }); document.querySelectorAll('.reveal').forEach(node => observer.observe(node)); window.addEventListener('scroll', onScroll, { passive: true }); return () => { observer.disconnect(); window.removeEventListener('scroll', onScroll); }; }, []);
  const closeMenu = () => setOpen(false);
  return <main className="landing-page">
    <header className={`public-nav ${scrolled ? 'public-nav-scrolled' : ''}`}><a className="public-brand" href="#top" onClick={closeMenu}><span>S</span>SurplusLink</a><button className="menu-toggle" aria-label="Toggle navigation menu" aria-expanded={open} onClick={() => setOpen(!open)}><i /><i /><i /></button><nav className={open ? 'open' : ''} aria-label="Public navigation">{['Home', 'Features', 'How it works', 'Sustainability'].map(label => <a key={label} href={`#${label.toLowerCase().replaceAll(' ', '-')}`} onClick={closeMenu}>{label}</a>)}<Link className="nav-login" to={accountPath} onClick={closeMenu}>{authenticated ? 'Open Dashboard' : 'Login'}</Link></nav></header>
    <section id="top" className="hero section-shell"><div className="hero-copy"><p className="pill">Construction materials, put back to work</p><h1>Give surplus materials<br />a <em>second life.</em></h1><p className="hero-intro">SurplusLink helps construction teams list reusable materials, find what their projects need, and make better reuse decisions with smart matching and logistics insights.</p><div className="hero-actions"><a className="cta primary" href="#how-it-works">See how it works <b>→</b></a><Link className="cta secondary" to={accountPath}>{authenticated ? 'Open Dashboard' : 'Login'}</Link></div><div className="hero-proof"><span><Icon name="layers" size={18} /> List surplus materials</span><span><Icon name="search" size={18} /> Find project needs</span><span><Icon name="compare" size={18} /> Compare smarter matches</span></div></div><div className="hero-visual" aria-label="Illustrative material matching preview"><div className="orb orb-one" /><div className="orb orb-two" /><div className="market-window"><div className="window-bar"><i /><i /><i /><span>Material match overview</span></div><div className="window-body"><div className="listing-card"><span className="tile-art"><Icon name="layers" size={28} /></span><div><small>AVAILABLE</small><strong>Floor Tiles</strong><b>500 m² · Verified</b></div></div><div className="match-line"><span>MATCH</span><b>92%</b></div><div className="buyer-card"><small>PROJECT NEED</small><strong>400 m² · Colombo</strong></div></div></div><div className="float-card route"><Icon name="pin" size={20} /><span><b>12.4 km away</b></span></div><div className="float-card verified"><Icon name="check" size={18} /> Verified listing</div><div className="float-card recommendation"><Icon name="compare" size={18} /> Recommended match</div></div></section>
    <section className="value-strip section-shell" aria-label="Platform value"><span><Icon name="recycle" /> <b>Reuse</b> more</span><span><Icon name="pin" /> <b>Source</b> locally</span><span><Icon name="package" /> <b>Reduce</b> waste</span><span><Icon name="compare" /> <b>Compare</b> options</span><span><Icon name="history" /> <b>Track</b> progress</span></section>
    <section id="features" className="section-shell section"><Reveal><p className="section-kicker">A better way to reuse materials</p><h2>From surplus to useful,<br />without the usual <em>friction.</em></h2><p className="section-lead">Bring available materials and project needs together in one clear workflow.</p></Reveal><div className="bento-grid bento-four">{features.map(([icon, title, copy, link], index) => <Reveal className={`feature-card feature-${index}`} key={title}><span className="feature-icon"><Icon name={icon} size={27} /></span><h3>{title}</h3><p>{copy}</p><span className="feature-mini">{link} →</span></Reveal>)}</div></section>
    <section id="how-it-works" className="section-shell section workflow-section"><Reveal><p className="section-kicker">Simple from the start</p><h2>How SurplusLink <em>works</em></h2></Reveal><div className="workflow workflow-three">{[['01','Share','List available materials or publish what your project needs.'],['02','Match','SurplusLink brings together compatible options and useful logistics information.'],['03','Review','Compare the recommendation, review the details and move forward through the controlled approval process.']].map(([n, title, copy]) => <Reveal className="workflow-step" key={n}><span>{n}</span><h3>{title}</h3><p>{copy}</p></Reveal>)}</div></section>
    <section className="section-shell section marketplace"><Reveal><p className="section-kicker">Explore what could be reused</p><h2>Materials worth another <em>project.</em></h2><p className="section-lead">From finishing materials to structural stock, SurplusLink makes reusable inventory easier to discover.</p></Reveal><div className="market-grid"><Reveal className="material-card tiles"><span>Finishes</span><div className="material-visual"><Icon name="layers" size={50} /></div><h3>Floor Tiles</h3><p>500 m² · LKR 800 / m²</p><b>Verified · Colombo</b></Reveal><Reveal className="material-card steel"><span>Structure</span><div className="material-visual"><Icon name="package" size={50} /></div><h3>Steel Bars</h3><p>1,200 kg · Kandy</p><b>Available</b></Reveal><Reveal className="material-card timber"><span>Timber</span><div className="material-visual"><Icon name="layers" size={50} /></div><h3>Reclaimed Timber</h3><p>350 units · Galle</p><b>Available</b></Reveal></div><p className="demo-note">Example listings shown for demonstration.</p><Reveal className="match-context"><span className="feature-icon"><Icon name="compare" size={27} /></span><div><h3>Smarter matching, useful context</h3><p>Compatible materials are compared using project requirements, availability and logistics information, helping teams focus on practical options.</p><small>Important actions remain subject to authorised review.</small></div></Reveal></section>
    <section className="section-shell section exchange"><Reveal><p className="section-kicker">Built for both sides of the exchange</p><h2>Have materials?<br />Need materials?<br /><em>SurplusLink connects the two.</em></h2></Reveal><div className="role-grid exchange-grid"><Reveal><article><span><Icon name="package" size={30} /></span><h3>For teams with surplus</h3><p>Make useful materials visible before they become waste, and keep quantities, locations and availability organised.</p></article></Reveal><Reveal><article><span><Icon name="search" size={30} /></span><h3>For teams sourcing materials</h3><p>Publish project needs and compare available materials that fit your requirements.</p></article></Reveal></div><p className="demo-note">The same account can support both activities where enabled.</p></section>
    <section id="sustainability" className="sustainability"><div className="section-shell"><Reveal><p className="section-kicker">Keep value in circulation</p><h2>Use what already <em>exists.</em></h2><p className="section-lead">Construction materials often still have value after their original purpose is finished. SurplusLink helps make that value visible so usable materials have a better chance of reaching another project.</p></Reveal><div className="impact-grid"><Reveal><div><b><Icon name="recycle" size={27} /></b><h3>Keep materials in use</h3></div></Reveal><Reveal><div><b><Icon name="package" size={27} /></b><h3>Reduce unnecessary disposal</h3></div></Reveal><Reveal><div><b><Icon name="pin" size={27} /></b><h3>Source closer to the project</h3></div></Reveal><Reveal><div><b><Icon name="layers" size={27} /></b><h3>Improve visibility of available stock</h3></div></Reveal></div></div></section>
    <section className="section-shell security"><Reveal><div className="clear-decisions"><span className="feature-icon"><Icon name="check" size={28} /></span><section><h3>Designed for clear decisions</h3><p>Listings, requirements, match information and workflow history stay connected, while important decisions remain under authorised human review.</p></section><ul><li>Verified listings</li><li>Transparent match details</li><li>Review before reservation</li></ul></div></Reveal></section>
    <section className="section-shell final-cta"><Reveal><div><p className="section-kicker">Put useful materials back to work</p><h2>Start with what you <em>already have.</em></h2><p>Make surplus visible, discover project needs and find better opportunities for material reuse.</p><div className="hero-actions"><Link className="cta primary" to={accountPath}>{authenticated ? 'Open Dashboard' : 'Login'} <b>→</b></Link><a className="cta secondary" href="#how-it-works">How it works</a></div></div></Reveal></section>
    <footer className="public-footer"><div className="section-shell"><div><a className="public-brand" href="#top"><span>S</span>SurplusLink</a><p>Construction material reuse, made easier.</p></div><div><b>Explore</b><a href="#how-it-works">How it works</a><a href="#features">Features</a><a href="#sustainability">Sustainability</a></div><div><b>Account</b><Link to={accountPath}>{authenticated ? 'Open dashboard' : 'Login'}</Link></div><div><p>© 2026 SurplusLink.</p><span>Built to support smarter construction material reuse.</span></div></div></footer>
  </main>;
}
