import { useEffect, useState, type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../auth/AuthContext';
import { roleHomePath } from '../routing/roleRoutes';

const heroImages = ['/images/hero/warehouse-timber.png', '/images/hero/reclamation-yard.png', '/images/hero/tiles-and-timber.png', '/images/hero/steel-loading-bay.png'];
type IconName = 'layers' | 'search' | 'route' | 'check' | 'recycle' | 'shield' | 'arrow';

function Icon({ name }: { name: IconName }) {
  const paths: Record<IconName, ReactNode> = {
    layers: <><path d="m12 3 8 4.5-8 4.5-8-4.5L12 3Z" /><path d="m4 12 8 4.5 8-4.5M4 16.5 12 21l8-4.5" /></>,
    search: <><circle cx="10.5" cy="10.5" r="6.5" /><path d="m16 16 4 4" /></>,
    route: <><circle cx="6" cy="18" r="2" /><circle cx="18" cy="6" r="2" /><path d="M8 18c7 0 1-8 8-10" /></>,
    check: <><circle cx="12" cy="12" r="9" /><path d="m8 12 2.5 2.5L16 9" /></>,
    recycle: <><path d="m7 7 2-3 2 3M9 4v7m6 6-2 3-2-3m2 3v-7M5 14l-2-3 3-2m-3 2h7m9 1 2 3-3 2m3-2h-7" /></>,
    shield: <><path d="M12 3 20 6v5c0 5-3.4 8.3-8 10-4.6-1.7-8-5-8-10V6l8-3Z" /><path d="m8.5 12 2.2 2.2 4.8-5" /></>,
    arrow: <path d="M5 12h13m-5-5 5 5-5 5" />,
  };
  return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>;
}

function Reveal({ children, className = '' }: { children: ReactNode; className?: string }) { return <div className={`landing-reveal ${className}`}>{children}</div>; }

export function LandingPage() {
  const { status, user } = useAuth(); const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false); const [activeSlide, setActiveSlide] = useState(0);
  const authenticated = status === 'authenticated' && user; const accountPath = user ? roleHomePath(user.roles) : '/login';
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 12); const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) entry.target.classList.add('is-visible'); }), { threshold: .12 }); document.querySelectorAll('.landing-reveal').forEach(node => observer.observe(node)); window.addEventListener('scroll', onScroll, { passive: true }); return () => { observer.disconnect(); window.removeEventListener('scroll', onScroll); }; }, []);
  useEffect(() => { if (window.matchMedia?.('(prefers-reduced-motion: reduce)').matches) return; const timer = window.setInterval(() => setActiveSlide(current => (current + 1) % heroImages.length), 6000); return () => window.clearInterval(timer); }, []);
  const closeMenu = () => setOpen(false);
  return <main className="landing-page premium-landing">
    <header className={`public-nav ${scrolled ? 'public-nav-scrolled' : ''}`}><a className="public-brand" href="#top" onClick={closeMenu}><img src="/images/brand/surpluslink-mark.png" alt="" />SurplusLink</a><button className="menu-toggle" type="button" aria-label="Toggle navigation menu" aria-expanded={open} onClick={() => setOpen(value => !value)}><i /><i /><i /></button><nav className={open ? 'open' : ''} aria-label="Public navigation">{['Home', 'Platform', 'How it works', 'Impact'].map(label => <a key={label} href={`#${label.toLowerCase().replaceAll(' ', '-')}`} onClick={closeMenu}>{label}</a>)}<Link className="nav-login" to={accountPath} onClick={closeMenu}>{authenticated ? 'Open Dashboard' : 'Login'}</Link></nav></header>
    <section id="top" className="hero hero-slideshow"><div className="hero-slides" aria-hidden="true">{heroImages.map((image, index) => <img key={image} src={image} className={index === activeSlide ? 'active' : ''} alt="" />)}</div><div className="hero-overlay" /><div className="hero-copy section-shell"><p className="pill">Construction materials, put back to work</p><h1>Turn Surplus Into <em>Opportunity.</em></h1><p className="hero-intro">Connect buyers and sellers of reusable construction materials with practical matching, logistics context, and accountable review.</p><div className="hero-actions"><Link className="cta primary" to={accountPath}>{authenticated ? 'Open Dashboard' : 'Login'} <Icon name="arrow" /></Link><a className="cta secondary" href="#how-it-works">Explore the platform</a></div><div className="hero-proof"><span><Icon name="layers" /> List useful materials</span><span><Icon name="search" /> Source for a project</span><span><Icon name="shield" /> Review with confidence</span></div><div className="hero-dots" role="tablist" aria-label="Hero images">{heroImages.map((_, index) => <button key={index} type="button" role="tab" aria-label={`Show hero image ${index + 1}`} aria-selected={index === activeSlide} onClick={() => setActiveSlide(index)} />)}</div></div></section>
    <section className="value-strip section-shell landing-reveal" aria-label="Platform value"><span><Icon name="recycle" /><b>Keep value</b> in circulation</span><span><Icon name="route" /><b>Plan logistics</b> earlier</span><span><Icon name="search" /><b>Compare</b> practical options</span><span><Icon name="shield" /><b>Keep decisions</b> accountable</span></section>
    <section id="platform" className="section-shell section platform-section"><Reveal><p className="section-kicker">A clearer material exchange</p><h2>More than a listing board. A better way to put materials back to work.</h2><p className="section-lead">SurplusLink brings reusable inventory, buyer requirements, matching context and controlled decisions together in one purposeful workspace.</p></Reveal><div className="platform-grid"><Reveal className="platform-story"><span className="feature-icon"><Icon name="layers" /></span><h3>Make useful surplus visible</h3><p>Capture quantity, condition, pricing, availability and location so materials can be discovered before they become waste.</p><ul><li>Organised construction inventory</li><li>Clear buyer requirements</li><li>Useful material context</li></ul></Reveal><Reveal className="platform-story dark"><span className="feature-icon"><Icon name="route" /></span><h3>Move from possibility to practical action</h3><p>Review matching and logistics context together, so teams can focus on options that are genuinely worth considering.</p><div className="decision-chips"><span>Matching</span><span>Logistics</span><span>Review</span></div></Reveal><Reveal className="platform-story accent"><span className="feature-icon"><Icon name="shield" /></span><h3>Keep important decisions human</h3><p>Recommendations support the process; authorised review continues to govern approvals and workflow decisions.</p></Reveal></div></section>
    <section id="how-it-works" className="landing-workflow"><div className="section-shell"><Reveal><p className="section-kicker">Simple from the start</p><h2>From material surplus to its next <em>purpose.</em></h2></Reveal><div className="workflow-steps-premium">{[['01', 'Share', 'List available materials or publish what your project needs, with the detail needed for a useful review.'], ['02', 'Compare', 'Explore compatible options with material, availability and logistics context in view.'], ['03', 'Review', 'Use the controlled workflow to make an informed, accountable decision.']].map(([number, title, copy]) => <Reveal className="workflow-step-premium" key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></Reveal>)}</div></div></section>
    <section id="features" className="section-shell section features-section"><Reveal><p className="section-kicker">Designed for considered reuse</p><h2>Every step has the right <em>context.</em></h2><p className="section-lead">A focused platform for teams with materials to share and projects with materials to source.</p></Reveal><div className="bento-grid bento-four">{[["layers", "List what you have", "Make reusable stock easier to understand with clear details and availability."], ["search", "Post what you need", "Describe the material, quantity, budget, deadline and project context."], ["route", "See logistics early", "Review distance, duration and transport information alongside the option."], ["check", "Decide with clarity", "Keep meaningful review and approval actions connected to the workflow."]].map(([icon, title, copy], index) => <Reveal className={`feature-card feature-${index}`} key={title}><span className="feature-icon"><Icon name={icon as IconName} /></span><h3>{title}</h3><p>{copy}</p><span className="feature-mini">Explore the workflow <Icon name="arrow" /></span></Reveal>)}</div></section>
    <section className="section-shell material-showcase"><Reveal><div><p className="section-kicker">Built around materials worth reusing</p><h2>From finishing stock to structural materials.</h2><p className="section-lead">SurplusLink helps turn overlooked construction inventory into visible opportunity across a range of reusable material types.</p></div></Reveal><div className="material-tiles">{[['Tiles and finishes', 'Ceramic, stone and fit-out materials'], ['Steel and structure', 'Sections, bars and usable metal stock'], ['Timber and components', 'Reclaimed wood, doors and useful fittings']].map(([title, copy], index) => <Reveal className={`material-tile tile-${index}`} key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p></Reveal>)}</div></section>
    <section id="impact" className="landing-impact"><div className="section-shell"><Reveal><p className="section-kicker">Keep value in circulation</p><h2>Use what already <em>exists.</em></h2><p className="section-lead">Construction materials often still have value after their first purpose. Making that value visible gives them a better chance of reaching another project.</p></Reveal><div className="impact-grid">{[['recycle', 'Keep materials in use'], ['layers', 'Reduce unnecessary disposal'], ['route', 'Source closer to the project'], ['search', 'Improve stock visibility']].map(([icon, title]) => <Reveal key={title}><div><b><Icon name={icon as IconName} /></b><h3>{title}</h3></div></Reveal>)}</div></div></section>
    <section className="section-shell final-cta"><Reveal><div><p className="section-kicker">Put useful materials back to work</p><h2>Start with what you already <em>have.</em></h2><p>Make surplus visible, discover project needs and create more opportunities for thoughtful construction material reuse.</p><div className="hero-actions"><Link className="cta primary" to={accountPath}>{authenticated ? 'Open Dashboard' : 'Login'} <Icon name="arrow" /></Link><a className="cta secondary" href="#how-it-works">How it works</a></div></div></Reveal></section>
    <footer className="public-footer"><div className="section-shell"><div><a className="public-brand" href="#top"><img src="/images/brand/surpluslink-mark.png" alt="" />SurplusLink</a><p>Construction material reuse, made easier.</p></div><div><b>Platform</b><a href="#platform">What it does</a><a href="#how-it-works">How it works</a><a href="#features">Why SurplusLink</a></div><div><b>Impact</b><a href="#impact">Keeping materials in use</a><a href="#features">Practical decisions</a></div><div><b>Account</b><Link to={accountPath}>{authenticated ? 'Open dashboard' : 'Login'}</Link><span>Built for smarter material reuse.</span></div></div></footer>
  </main>;
}
