import { useCallback, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useAuth } from '../auth/AuthContext';
import { transactionsApi, type Page, type TransactionHistoryEntry, type TransactionsApi } from '../features/transactions/transactionsApi';
import { RequirementBadge, RequirementError, requirementDate, requirementNumber, useRequirementResource } from '../features/requirements/requirementUi';

export function OfferDetailsPage({ api = transactionsApi }: { api?: TransactionsApi }) {
  const { offerId = '' } = useParams(); const { user } = useAuth();
  const [historyPage, setHistoryPage] = useState(1);
  const offers = useRequirementResource(useCallback(() => api.offer(offerId), [api, offerId]));
  const offer = offers.data;
  const transactions = useRequirementResource(useCallback(() => api.transactions({ offerId, page: 1, pageSize: 1, sortBy: 'createdAt', sortDir: 'desc' }), [api, offerId]));
  const transaction = transactions.data?.items.find(item => item.offerId === offerId);
  const history = useRequirementResource<Page<TransactionHistoryEntry>>(useCallback(() => transaction ? api.history(transaction.id, historyPage) : Promise.resolve({ items: [], total: 0, page: 1, pageSize: 20, totalPages: 0 }), [api, transaction?.id, historyPage]));
  return <div className="manager-page"><Link className="back-link" to="/app/offers">Back to My Offers</Link><header className="page-heading"><div><p className="eyebrow">Offer details</p><h1>{offer ? `Offer ${offer.id.slice(0, 8)}` : 'Offer details'}</h1></div></header>
    {offers.loading && <p role="status">Loading offer...</p>}{offers.error && <RequirementError message={offers.error} retry={offers.reload} />}
    {!offers.loading && !offers.error && !offer && <p className="empty-state">This offer is not available in your buyer or seller activity.</p>}
    {offer && <><section className="manager-panel"><div className="section-heading"><h2>Participation context</h2><RequirementBadge status={offer.status} /></div><dl className="detail-grid"><div><dt>Buyer</dt><dd>{offer.buyerId === user?.id ? 'You' : offer.buyerId}</dd></div><div><dt>Seller</dt><dd>{offer.sellerId === user?.id ? 'You' : offer.sellerId}</dd></div><div><dt>Quantity</dt><dd>{requirementNumber(offer.quantity)}</dd></div><div><dt>Unit value</dt><dd>{requirementNumber(offer.unitValue, 2)}</dd></div><div><dt>Total value</dt><dd>{requirementNumber(offer.totalValue, 2)}</dd></div><div><dt>Created</dt><dd>{requirementDate(offer.createdAt)}</dd></div></dl><p className="muted">Manager approval controls are intentionally unavailable in the marketplace workspace.</p></section>
      <section className="manager-panel"><div className="section-heading"><h2>Transaction and reservation status</h2>{transaction && <RequirementBadge status={transaction.status} />}</div>{transactions.loading && <p role="status">Loading transaction status...</p>}{transactions.error && <RequirementError message={transactions.error} retry={transactions.reload} />}{!transactions.loading && !transaction && <p className="empty-state">No transaction has been created for this offer yet.</p>}{transaction && <dl className="detail-grid"><div><dt>Reserved quantity</dt><dd>{requirementNumber(transaction.reservedQuantity)}</dd></div><div><dt>Transaction value</dt><dd>{requirementNumber(transaction.totalValue, 2)}</dd></div><div><dt>Updated</dt><dd>{requirementDate(transaction.updatedAt)}</dd></div><div><dt>Completed</dt><dd>{transaction.completedAt ? requirementDate(transaction.completedAt) : 'Not completed'}</dd></div></dl>}</section>
      <section className="manager-panel"><div className="section-heading"><h2>History</h2>{history.data && <span className="muted">{history.data.total} events</span>}</div>{history.loading && <p role="status">Loading history...</p>}{history.error && <RequirementError message={history.error} retry={history.reload} />}{history.data && (history.data.items.length === 0 ? <p className="empty-state">No transaction history yet.</p> : <ol className="history-list">{history.data.items.map((event: TransactionHistoryEntry) => <li key={event.id}><strong>{event.action.replaceAll('_', ' ')}</strong><time dateTime={event.createdAt}>{requirementDate(event.createdAt)}</time><span>{event.actorUserId === user?.id ? 'Your action' : event.actorUserId ? 'Marketplace action' : 'System action'}</span></li>)}</ol>)}{history.data && history.data.totalPages > 1 && <div className="pagination"><button className="button button-secondary" disabled={historyPage <= 1} onClick={() => setHistoryPage(historyPage - 1)} type="button">Previous</button><span>Page {historyPage} of {history.data.totalPages}</span><button className="button button-secondary" disabled={historyPage >= history.data.totalPages} onClick={() => setHistoryPage(historyPage + 1)} type="button">Next</button></div>}</section></>}
  </div>;
}
