import { formatLkr } from '../utils/currency';
import { useCallback, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useAuth } from '../auth/AuthContext';
import { transactionConfirmationsApi, transactionsApi, type Page, type TransactionHistoryEntry, type TransactionsApi } from '../features/transactions/transactionsApi';
import { RequirementBadge, RequirementError, requirementDate, requirementNumber, useRequirementResource } from '../features/requirements/requirementUi';

export function OfferDetailsPage({ api = transactionsApi }: { api?: TransactionsApi }) {
  const { offerId = '' } = useParams(); const { user } = useAuth();
  const [historyPage, setHistoryPage] = useState(1);
  const [acting, setActing] = useState(false);
  const offers = useRequirementResource(useCallback(() => api.offer(offerId), [api, offerId]));
  const offer = offers.data;
  const transactions = useRequirementResource(useCallback(() => api.transactions({ offerId, page: 1, pageSize: 1, sortBy: 'createdAt', sortDir: 'desc' }), [api, offerId]));
  const transaction = transactions.data?.items.find(item => item.offerId === offerId);
  const history = useRequirementResource<Page<TransactionHistoryEntry>>(useCallback(() => transaction ? api.history(transaction.id, historyPage) : Promise.resolve({ items: [], total: 0, page: 1, pageSize: 20, totalPages: 0 }), [api, transaction?.id, historyPage]));
  return <div className="manager-page"><Link className="back-link" to="/app/offers">Back to My Offers</Link><header className="page-heading"><div><p className="eyebrow">Offer details</p><h1>{offer ? offer.materialName || offer.requirementTitle || 'Offer details' : 'Offer details'}</h1></div></header>
    {offers.loading && <p role="status">Loading offer...</p>}{offers.error && <RequirementError message={offers.error} retry={offers.reload} />}
    {!offers.loading && !offers.error && !offer && <p className="empty-state">This offer is not available in your buyer or seller activity.</p>}
    {offer && <><section className="manager-panel"><div className="section-heading"><h2>Offer summary</h2><RequirementBadge status={offer.status} /></div><small className="requirement-id">Reference: #{offer.id.slice(0, 8)}</small><dl className="detail-grid"><div><dt>Material</dt><dd>{offer.materialName || offer.requirementTitle || 'Material unavailable'}</dd></div><div><dt>Buyer</dt><dd>{offer.buyerName || (offer.buyerId === user?.id ? 'You' : 'Buyer name unavailable')}</dd></div><div><dt>Seller</dt><dd>{offer.sellerBusinessName || offer.sellerName || (offer.sellerId === user?.id ? 'You' : 'Seller name unavailable')}</dd></div><div><dt>Quantity</dt><dd>{requirementNumber(offer.quantity)} {offer.unit}</dd></div><div><dt>Unit value</dt><dd>{formatLkr(offer.unitValue)}</dd></div><div><dt>Material value</dt><dd>{formatLkr(offer.totalValue)}</dd></div><div><dt>Created</dt><dd>{requirementDate(offer.createdAt)}</dd></div><div><dt>Updated</dt><dd>{requirementDate(offer.updatedAt)}</dd></div></dl><p className="muted">Manager approval controls are intentionally unavailable in the marketplace workspace.</p></section>
      <section className="manager-panel"><div className="section-heading"><h2>Transaction and reservation status</h2>{transaction && <RequirementBadge status={transaction.status} />}</div>{transactions.loading && <p role="status">Loading transaction status...</p>}{transactions.error && <RequirementError message={transactions.error} retry={transactions.reload} />}{!transactions.loading && !transaction && <p className="empty-state">No transaction has been created for this offer yet.</p>}{transaction && <><dl className="detail-grid"><div><dt>Reserved quantity</dt><dd>{requirementNumber(transaction.reservedQuantity)} {offer.unit}</dd></div><div><dt>Transaction value</dt><dd>{formatLkr(transaction.totalValue)}</dd></div><div><dt>Confirmation deadline</dt><dd>{transaction.confirmationDeadline ? requirementDate(transaction.confirmationDeadline) : 'Unavailable'}</dd></div><div><dt>Seller handover</dt><dd>{transaction.sellerHandoverConfirmedAt ? `Handed over on ${requirementDate(transaction.sellerHandoverConfirmedAt)}` : 'Waiting for Seller to confirm handover.'}</dd></div><div><dt>Buyer receipt</dt><dd>{transaction.buyerReceivedConfirmedAt ? `Received on ${requirementDate(transaction.buyerReceivedConfirmedAt)}` : transaction.sellerHandoverConfirmedAt ? 'Waiting for Buyer to confirm receipt.' : 'Not available yet'}</dd></div></dl>
        {transaction.sellerId === user?.id && transaction.status === 'APPROVED' && !transaction.sellerHandoverConfirmedAt && <button type="button" className="button" disabled={acting} onClick={() => { setActing(true); void transactionConfirmationsApi.handover(transaction.id).then(transactions.reload).then(history.reload).finally(() => setActing(false)); }}>Handed Over</button>}
        {transaction.buyerId === user?.id && transaction.status === 'HANDED_OVER' && transaction.sellerHandoverConfirmedAt && !transaction.buyerReceivedConfirmedAt && <button type="button" className="button" disabled={acting} onClick={() => { setActing(true); void transactionConfirmationsApi.confirmReceipt(transaction.id).then(transactions.reload).then(history.reload).finally(() => setActing(false)); }}>Received</button>}
      </>}</section>
      <section className="manager-panel"><div className="section-heading"><h2>History</h2>{history.data && <span className="muted">{history.data.total} events</span>}</div>{history.loading && <p role="status">Loading history...</p>}{history.error && <RequirementError message={history.error} retry={history.reload} />}{history.data && (history.data.items.length === 0 ? <p className="empty-state">No transaction history yet.</p> : <ol className="history-list">{history.data.items.map((event: TransactionHistoryEntry) => <li key={event.id}><strong>{event.action.replaceAll('_', ' ')}</strong><time dateTime={event.createdAt}>{requirementDate(event.createdAt)}</time><span>{event.transactionReference} · {event.itemTitle} · {event.quantity} {event.unit}</span><span>{event.actorUserId === user?.id ? 'Your action' : event.actorUserId ? 'Marketplace action' : 'System action'}</span>{event.note && <span>{event.note}</span>}</li>)}</ol>)}{history.data && history.data.totalPages > 1 && <div className="pagination"><button className="button button-secondary" disabled={historyPage <= 1} onClick={() => setHistoryPage(historyPage - 1)} type="button">Previous</button><span>Page {historyPage} of {history.data.totalPages}</span><button className="button button-secondary" disabled={historyPage >= history.data.totalPages} onClick={() => setHistoryPage(historyPage + 1)} type="button">Next</button></div>}</section></>}
  </div>;
}
